name: Angular Build

on:
  workflow_call:

jobs:
  angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Npm install
        run: |
          npm install

      - name: Build
        run: npm run build:prod

      - name: Upload angular-dist
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          retention-days: 1
          path: |
            ./dist