name: Angular Unit Test

on:
  workflow_call:

jobs:
  angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Download angular-dist
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: .

      - name: Unit Test
        run: npm run test