name: Angular Tag

on:
  workflow_call:

jobs:
  angular:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download angular-dist
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: .

      - name: App Version
        run: |
          echo "VERSION=$(grep -o 'this.appVersion=".*",' ./dist/*/main*.js | awk -F '"' '{print $2}')" >> $GITHUB_ENV

      - name: Tag Version
        uses: butlerlogic/action-autotag@1.1.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          version: "${{ env.VERSION }}"
