name: API First Generate

on:
  workflow_call:
    secrets:
      MAVEN_USER:
        required: true
      MAVEN_TOKEN:
        required: true

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}/.m2

      - name: Download artefactory
        uses: actions/download-artifact@v3
        with:
          name: maven-settings
          path: ${{ github.workspace }}/.m2

      - name: Maven version
        run: |
          mvn -v
          cat ${{ github.workspace }}/.m2/settings.xml

      - name: Build with Deploy
        run: mvn -e -B deploy -s ${{ github.workspace }}/.m2/settings.xml

      - name: Tag Version
        uses: butlerlogic/action-autotag@stable
        with:
          strategy: regex
          root: target/maven-archiver/pom.properties
          regex_pattern: 'version=(\S.*)'
