name: API First Generate

on:
  workflow_call:
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  api:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
          
      - name: Generate Client & Stub version SNAPSHOST (only develop)
        if: github.ref == 'refs/heads/develop'
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: spring
          openapi-file: apis/gaptia-rest.yml
          command-args: >
            --output target 
            --group-id org.gaptia 
            --artifact-id app-gaptia 
            --package-name app-gaptia
            --api-package org.gaptia
            --additional-properties=snapshotVersion=true
            
      - name: Generate Client & Stub version STABLE (only main)
        if: github.ref == 'refs/heads/main'
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: spring
          openapi-file: apis/gaptia-rest.yml
          command-args: >
            --output target 
            --group-id org.gaptia 
            --artifact-id app-gaptia 
            --package-name app-gaptia
            --api-package org.gaptia
            --additional-properties=snapshotVersion=false
            
      - name: View pom.xml
        run: |
          cat target/pom.xml

      - name: Tag Version
        uses: butlerlogic/action-autotag@stable
        with:
          strategy: regex
          root: target/pom.xml
          regex_pattern: '<version>([^<]+)<'

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Publish Packages
        run: |
          cd target
          mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/patricia-gp/app-gaptia  
