name: API First Generate

on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
  
      - name: Build with Maven
        run: mvn -B package

      - name: Tag Version
        uses: butlerlogic/action-autotag@stable
        with:
          strategy: regex
          root: target/maven-archiver/pom.properties
          regex_pattern: 'version=(\S.*)'
  
      - name: Publish Packages
        run: mvn -B deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }}
