name: Api Tag Generate

on:
  workflow_call:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Download artefactory
        uses: actions/download-artifact@v3
        with:
          name: api-target
          path: target

      - name: Tag Version
        uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          strategy: regex
          root: target/maven-archiver/pom.properties
          regex_pattern: 'version=(\S.*)'
