name: API First Generate

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-yelp"
  openapi:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Client & Stub version SNAPSHOST (only develop)
        if: github.ref == 'refs/heads/develop'
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: spring
          openapi-file: apis/gaptia-rest.yml
          command-args: >
            --output target 
            --group-id org.gaptia 
            --artifact-id app-gaptia 
            --package-name app-gaptia
            --api-package org.gaptia
            --additional-properties=snapshotVersion=true
            
      - name: Generate Client & Stub version STABLE (only main)
        if: github.ref == 'refs/heads/main'
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: spring
          openapi-file: apis/gaptia-rest.yml
          command-args: >
            --output target 
            --group-id org.gaptia 
            --artifact-id app-gaptia 
            --package-name app-gaptia
            --api-package org.gaptia
            --additional-properties=snapshotVersion=false
            
      - name: View pom.xml
        run: |
          cat target/pom.xml

      - name: Tag Version
        uses: butlerlogic/action-autotag@stable
        with:
          strategy: regex
          root: target/pom.xml
          regex_pattern: '<version>([^<]+)<'

      - name: Publish Packages
        if: github.ref == 'refs/heads/main'
        run: |
          cd target
          mvn deploy      
