name: API Spring Generate

on:
  workflow_call:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ~/.m2
          cache: 'maven'

      - name: Download maven-m2
        uses: actions/download-artifact@v3
        with:
          name: maven-m2
          path: ~/.m2

      - name: Maven version
        run: |
          mvn -v

      - name: Build with Deploy
        run: mvn -e -B deploy

      - name: Upload api-properties
        uses: actions/upload-artifact@v3
        with:
          name: api-properties
          path: target/maven-archiver/pom.properties
