name: API First Generate

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-yelp"
  openapi:

    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Client & Stub Java
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: java
          config-file: gaptia-rest.yml
          outputDir: target/gaptia-client-java

      # Do something with the generated client (likely publishing it somewhere)
      - name: Do something with the client
        run: |
          cd target/gaptia-client-java
          ls -l
