name: API First Generate

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-yelp"
  openapi:

    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-api-generator .

    - name: Generate API
      run: docker run --rm my-api-generator generate-api -f api.yaml
