name: API First Generate

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-yelp"
  openapi:

    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3

      # Run OpenAPI
      - name: Generate API-First with OpenAPI
        run: docker build -t my-api-generator .

      - name: Generate API
        uses: patricia-gp/gha-gaptia/actions/api-first-generate@main
