name: Code Tag

on:
  workflow_call:

jobs:
  code:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download spring-target
        uses: actions/download-artifact@v4
        with:
          name: spring-target
          path: ./target

      - name: Pom Properties
        run: |
          cat ./target/maven-archiver/pom.properties

      - name: Get now
        run: echo "NOW=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Tag Version
        uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          strategy: regex
          root: ./target/maven-archiver/pom.properties
          regex_pattern: 'version=(\S.*)'
          tag_prefix: "v"
          tag_suffix: "-${{ env.NOW }}"
