# This is a basic workflow to help you get started with Actions

name: Hello

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build-hello:
  
    # The type of runner that the job will run on
    name: Hello
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
