name: Hello

on:
  workflow_call:
    secrets:
      MAVEN_USER:
        required: true
      MAVEN_TOKEN:
        required: true
      GITHUB_TOKEN:
        GITHUB_TOKEN: true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
