
name: Maven Settings Generate

on:
  workflow_call:

  workflow_dispatch:

jobs:

  repository:
    runs-on: ubuntu-latest
    steps:
    
    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v21
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        output_file: .m2/settings.xml
        active_profiles: '[ "github" ]'
        servers: >
          [
            {
              "id": "github",
              "username": "${env.MAVEN_USER}",
              "password": "{env.MAVEN_TOKEN}"
            }
          ]
        repositories: >
          [
            {
              "id": "central",
              "url": "https://repo1.maven.org/maven2"
            },
            {
              "id": "github",
              "url": "https://maven.pkg.github.com/patricia-gp/api-gaptia"
            }
          ]        
    
    - name: View settings.xml
      run: |
        cat .m2/settings.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: maven-settings
        path: .m2
