name: Maven Settings Generate

on:
  workflow_call:
    secrets:
      MAVEN_USER:
        required: true
      MAVEN_TOKEN:
        required: true

  workflow_dispatch:

jobs:
  repository:
    runs-on: ubuntu-latest
    steps:
      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          output_file: ./settings.xml
          active_profiles: '[ "github" ]'
          servers: >
            [
              {
                "id": "github",
                "username": "${{ secrets.MAVEN_USER || 'YOUR_USERNAME' }}",
                "password": "${{ secrets.MAVEN_TOKEN || 'YOUR_PERSONAL_ACCESS_TOKEN' }}"
              }
            ]
          repositories: >
            [
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/patricia-gp/api-gaptia"
              }
            ]        

      - name: View settings.xml
        run: |
          cat ./settings.xml

      - name: Upload maven-m2
        uses: actions/upload-artifact@v3
        with:
          name: maven-m2
          path: ./settings.xml
