
name: Maven Settings Generate

on:
  workflow_dispatch:

jobs:

  settings:
    runs-on: ubuntu-latest
    steps:
    
    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        repositories: >
          [
            {
              "id": "central",
              "url": "https://repo1.maven.org/maven2"
            },
            {
              "id": "app-gaptia",
              "url": "https://maven.pkg.github.com/patricia-gp/app-package"
            }
          ]
        servers: >
          [
            {
              "id": "github",
              "username": "${ env.GITHUB_USER }",
              "password": "${ env.GITHUB_TOKEN }"
            }
          ]
        profiles: >
          [
            {
              "id": "gaptia"
            }
          ]
        active_profiles: >
          [
            "gaptia"
          ]
        output_file: .m2/settings.xml
    
    - name: View settings.xml
      run: |
        cat .m2/settings.xml
