name: Microservice Spring Unit Test

on:
  workflow_call:

jobs:
  mic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Download maven-settings
        uses: actions/download-artifact@v3
        with:
          name: maven-settings
          path: ~/.m2

      - name: Download mic-target
        uses: actions/download-artifact@v3
        with:
          name: mic-target
          path: ./target

      - name: Unit test
        run: mvn -e -B test -Dsnyk.skip=true