name: Microservice Spring Unit Test

on:
  workflow_call:
    inputs:
      SONAR_HOST_URL:
        type: string
        required: true
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  mic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Download mic-target
        uses: actions/download-artifact@v3
        with:
          name: mic-target
          path: ./target

      - name: Sonar
        run: mvn -e -B verify sonar:sonar -DskipTestsIT=true -Dsnyk.skip=true -Dsonar.host.url=${{ inputs.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.qualitygate.wait=true