name: Microservice Spring Unit Test

on:
  workflow_call:
    inputs:
      SONAR_HOST_URL:
        type: string
        required: true

jobs:
  mic:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}/.m2

      - name: Download artefactory
        uses: actions/download-artifact@v3
        with:
          name: mic-workspace
          path: ${{ github.workspace }}

      - name: Url sonar
        run: echo Sonar, ${{ inputs.SONAR_HOST_URL }}

      - name: Sonar
        run: mvn -e -o -B sonar:sonar -s ${{ github.workspace }}/.m2/settings.xml -Dsonar.host.url=${{ inputs.SONAR_HOST_URL }}