name: Secret Detection

on:
  workflow_call:

env:
  MAVEN_USER: ${{ secrets.MAVEN_USER }}
  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
        
      - name: Scan secrets with Yelp
        uses: patricia-gp/gha-gaptia/actions/secret-detection@main
