
name: Secret Detection

on:
  workflow_call:

jobs:
  
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        
  yelp:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: View dir
        run: |
          ls -l
      - name: Scan secrets with Yelp
        uses: patricia-gp/gha-gaptia/actions/secret-detection@main
