
name: Secret Detection

# Controls when the workflow will run
on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build-yelp"
  build-yelp:
  
    # The type of runner that the job will run on
    name: Detect Secrets - Yelp
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3

      # Run Yelp
      - name: Install detect-secrets with Yelp
        id: detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0 

      # Commit .secrets.baseline
      - name: Commit back .secrets.baseline (if it was missing)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Commit the newly-generated .secrets.baseline file"

      - name: Check Result
        run: |
          if [[ "${{ steps.detect-secrets.outputs.has_secrets }}" == "true" ]]; then
            echo "Potential secrets detected in the code."
            exit 1
          fi
