name: Secret Detection

on:
  workflow_call:
    secrets:
      MAVEN_USER:
        required: true
      MAVEN_TOKEN:
        required: true

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
        
      - name: Scan secrets with Yelp
        uses: patricia-gp/gha-gaptia/actions/secret-detection@main
