name: Spring Tag

on:
  workflow_call:

jobs:
  spring:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download spring-target
        uses: actions/download-artifact@v4
        with:
          name: spring-target
          path: .

      - name: Pom Properties
        run: |
          cat ./target/maven-archiver/pom.properties

      - name: Tag Version
        uses: butlerlogic/action-autotag@1.1.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          strategy: regex
          root: ./target/maven-archiver/pom.properties
          regex_pattern: 'version=(\S.*)'
