name: Spring Scanner Sonar

on:
  workflow_call:
    inputs:
      SONAR_HOST_URL:
        type: string
        required: true
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  spring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          output_file: ./settings.xml
          active_profiles: '[ "github" ]'
          servers: >
            [
              {
                "id": "github",
                "username": "${{ secrets.MAVEN_USER || 'YOUR_USERNAME' }}",
                "password": "${{ secrets.MAVEN_TOKEN || 'YOUR_PERSONAL_ACCESS_TOKEN' }}"
              }
            ]
          repositories: >
            [
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/patricia-gp/api-gaptia"
              }
            ]        

      - name: View settings.xml
        run: |
          cat ./settings.xml

      - name: Download spring-target
        uses: actions/download-artifact@v4
        with:
          name: spring-target
          path: ./target

      - name: Sonar
        run: mvn -e -B verify sonar:sonar -DskipTestsIT=true -Dsnyk.skip=true -Dsonar.host.url=${{ inputs.SONAR_HOST_URL }} -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.qualitygate.wait=true