name: Spring Scanner Snyk

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  spring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Download spring-target
        uses: actions/download-artifact@v4
        with:
          name: spring-target
          path: .

      - name: Permission mvnw
        run: |
          mvn -v
          git update-index --chmod=+x ./mvnw

      - name: Snyk
        run: mvn -e -B install -DskipTests=true -DskipTestsIT=true -Dsnyk.token=${{ secrets.SNYK_TOKEN }}