name: Spring Instance AWS

on:
  workflow_call:
    inputs:
      AWS_REGION:
        type: string
        required: true
      AWS_ECR_REPOSITORY:
        type: string
        required: true
      AWS_ECS_CLUSTER:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  spring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download spring-target
        uses: actions/download-artifact@v3
        with:
          name: spring-target
          path: ./target

      - name: App Name & Version
        id: app-version
        run: |
          echo "APP=$(echo $(cat ./target/maven-archiver/pom.properties | awk -F'artifactId=' '{print $2}'))" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo $(cat ./target/maven-archiver/pom.properties | awk -F'version=' '{print $2}'))" >> $GITHUB_OUTPUT

      - name: Build Docker & Push to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.app-version.outputs.VERSION }}
        run: |          
          echo "Building Docker $ECR_REPOSITORY:$IMAGE_TAG ..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing Docker ...
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

