name: Spring Integration Test

on:
  workflow_call:

jobs:
  spring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ${{ github.repository }} Brach ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Download spring-target
        uses: actions/download-artifact@v4
        with:
          name: spring-target
          path: .

      - name: List
        run: |
          echo 'pgp----------------------------------pgp'
          ls /home/runner/work/mic-gaptia/mic-gaptia/e2e
          echo 'pgp----------------------------------pgp'
          cat /home/runner/work/mic-gaptia/mic-gaptia/e2e/docker-compose.yaml

      - name: Integration test
        run: mvn -e -B verify -Ptest -DskipTests=true -Dsnyk.skip=true
